version: "3.4"
services:
  back:
    image: fgdou/esirjam-back
  front:
    image: fgdou/esirjam-front
  nginx:
    image: fgdou/esirjam-nginx
    ports:
      - 80:80
    depends_on:
      - front
      - back