version: "3.4"
services:
  back:
    image: fgdou/esirjam-back
    build:
      context: .
      target: BACK
    depends_on:
      - db
    environment:
      - DB_PASSWORD=$DB_PASSWORD
      - DB_USER=$DB_USER
      - DB_DB=$DB_DB
      - DB_PORT=$DB_PORT
      - DB_HOST=$DB_HOST

  front:
    image: fgdou/esirjam-front
    build:
      context: .
      target: FRONT

  db:
    image: postgres:15.2
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_DB
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  nginx:
    image: fgdou/esirjam-nginx
    build: nginx
    ports:
      - 80:80
    depends_on:
      - front
      - back
volumes:
  db: