version: "3.4"
services:
  back:
    image: fgdou/esirjam-back
    environment:
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_DB=wordjam
      - DB_PORT=5432
  front:
    image: fgdou/esirjam-front
  nginx:
    image: fgdou/esirjam-nginx
    ports:
      - 80:80
    depends_on:
      - front
      - back
  db:
    image: postgres:15.2
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=wordjam

volumes:
  db: