version: "3.4"
services:
  back:
    image: fgdou/esirjam-back
    environment:
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_DB=wordjam
      - DB_PORT=5432
      - DB_HOST=db
      - SAVE_DELAY_SECONDS=60
    depends_on:
      - db
    restart: always
  front:
    image: fgdou/esirjam-front
    restart: always
  nginx:
    image: fgdou/esirjam-nginx
    ports:
      - 80:80
    depends_on:
      - front
      - back
    restart: always
  db:
    image: postgres:15.2
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=wordjam
    restart: always

volumes:
  db: