version: "3.4"
services:
  back:
    image: fgdou/esirjam-back
    build:
      context: .
      target: BACK
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DB=$DB_DB
      - DB_PORT=$DB_PORT
      - DB_HOST=$DB_HOST
      - SAVE_DELAY_SECONDS=$SAVE_DELAY_SECONDS=10
    depends_on:
      - db

  front:
    image: fgdou/esirjam-front
    build:
      context: .
      target: FRONT
  api:
    image: fgdou/esirjam-api
    build: apps/api
    restart: always
    ports:
      - 3001:3001
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/wordjam?schema=public
  nginx:
    image: fgdou/esirjam-nginx
    build: nginx
    ports:
      - 80:80
    depends_on:
      - front
      - back
      - api
  db:
    image: postgres:15.2
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_DB
    ports:
      - 5432:5432
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8081:8080


volumes:
  db:
