import './globals.css';
import { uiFont } from '@/src/utils/fontLoader';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className={`h-full ${uiFont.className}`}>
      <body className='h-full'>{children}</body>
    </html>
  );
}
