export enum PlacedResponse {
    OK = "OK",
    PLAYER_DONT_HAVE_LETTERS = "PLAYER_DONT_HAVE_LETTERS",
    INVALID_POSITION = "INVALID_POSITION",
    WORD_NOT_EXIST = "WORD_NOT_EXIST",
    WORD_NOT_CONNECTED_TO_OTHERS = "WORD_NOT_CONNECTED_TO_OTHERS",
    NO_LETTER_IN_REQUEST = "NO_LETTER_IN_REQUEST",
}